if k8s_context() != 'minikube':
  fail("K8s context is not minikube")

allow_k8s_contexts(contexts = ["minikube"])

local_resource(name = 'broken-ns',
    cmd = 'kubectl get namespace | grep -q "^broken" || kubectl create namespace broken',
    labels = ["broken"]
)

local_resource(name = 'broken-app-manifest', 
    cmd = 'kubectl apply -f local/minikube/application.yml \
        && sleep 10 && kubectl wait apps/broken-app -n argo-cd --for=jsonpath=\'{.status.health.status}\'=Healthy --timeout=90s',
    resource_deps = ["broken-ns", "argo-rollouts-app-manifest", "argocd-server", "argocd-application-controller", "argocd-repo-server"],
    labels = ["broken"]
) 
