apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-cd
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
