apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: broken-app
  namespace: argo-cd
spec:
  project: broken
  source:
    repoURL: https://github.com/jmmclean/k8s-local-tilt.git
    targetRevision: lab-broken-app
    path: broken-app/local/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: broken
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
