# Allow kustomize to modify helm generated manifests
#   Ref: https://github.com/argoproj/argo-cd/issues/2789#issuecomment-960271294
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
    - kube-controller-manager
    jsonPointers:
    - /spec/replicas
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
