apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  admin.password: "$2a$10$rhM/6wcNTTbXXmHJMyqHUuMZPf47ML8bIBFOXly2S45Qe1X1vPao6"
  admin.passwordMtime: "2025-01-28T08:52:23EST"
